[project]
name = "repetiprompter"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "ollama>=0.6.1",
    "pydantic>=2.12.5",
    "pyyaml>=6.0.3",
    "typer>=0.21.0",
]
